server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
      
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-jt-web #服务的名称不能重复
  registry:
    address: zookeeper://192.168.206.129:2181?backup=192.168.206.129:2182,192.168.206.129:2183      


  